---
- name: Install udev rules for teen dev USB
  ansible.builtin.copy:
    src: udev/99-teen-dev-usb.rules
    dest: /etc/udev/rules.d/99-teen-dev-usb.rules
    mode: "0644"
  notify:
    - Reload udev rules
    - Trigger udev
